### ISSUE TITLE
WP_Widget constructor method is deprecated

### ISSUE THREAD

**Issue by pattwala** [MattGeri/wp-most-popular#23]
With WP_DEBUG set to true, WordPress throws the following notice:

*Notice:  The called constructor method for WP_Widget is deprecated since version 4.3.0! Use __construct() instead.*

In /wp-most-popular/system/widget.php, line 4 should be changed to:

parent::__construct( 'wmp_widget', 'WP Most Popular', array( 'description' => 'Display your most popular blog posts on your sidebar' ) );

**Comment by MattGeri** [comment]
Thanks for this, will be sorted out this week.

**Comment by MattGeri** [comment]
Fixed in 0.3
